# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Commity < Formula
  desc "AI-powered git commit message generator with TUI"
  homepage "https://github.com/hluaguo/commity"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hluaguo/commity/releases/download/v0.1.3/commity_0.1.3_darwin_amd64.tar.gz"
      sha256 "1711683ebc81d805e9562dc2d47b9c990825cc9d540d5808e3f59b3aef5d4725"

      def install
        bin.install "commity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hluaguo/commity/releases/download/v0.1.3/commity_0.1.3_darwin_arm64.tar.gz"
      sha256 "4bae9932983f9be47de6552ad971c123cff6530ad44a7dadb27ba88793d078d1"

      def install
        bin.install "commity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hluaguo/commity/releases/download/v0.1.3/commity_0.1.3_linux_amd64.tar.gz"
      sha256 "75ed7051345cb6353a5a199c2722d4ea9f965ee81192bcccb70208f1bd63740d"
      def install
        bin.install "commity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hluaguo/commity/releases/download/v0.1.3/commity_0.1.3_linux_arm64.tar.gz"
      sha256 "c9c43603ac20f857d5038513a9b2e7f18436629afad41a533c907046d5fee85c"
      def install
        bin.install "commity"
      end
    end
  end

  test do
    system "#{bin}/commity", "--version"
  end
end
